### PR TITLE
add more tag

### PR DESCRIPTION
**Pull request by hacke2**
新增
```
<!--more-->
```
标签

### CODE REVIEW

**Comment by UltCombo** [comment]
Thanks!
There's a small problem though: your PR is erasing 2 other files (see the ["files" tab](https://github.com/es6rocks/es6rocks.github.io/pull/55/files)).
You can fix that, or I can merge your changes manually if you'd prefer.

**Comment by UltCombo** [comment]
I mean, the articles inside the `pt-br` dir shouldn't be modified.
If you don't mind, I can it for you.

**Comment by hacke2** [comment]
OK，Please help me fix it : )

**Comment by UltCombo** [comment]
I pulled your commit, modified it a bit and pushed it while keeping your commit's authorship data: https://github.com/es6rocks/es6rocks.github.io/commit/be6d57e74874aed1eb36c7eef10a39c4507ab195
Thanks!

---

For future contributions, please make new branches using the upstream (this repository)'s `src` branch as base:

```
# add upstream remote if you haven't yet:
git remote add upstream https://github.com/es6rocks/es6rocks.github.io.git

# then before you start working on a new PR, update the remote and make a new branch off it:
git fetch upstream
git checkout -b my-new-branch upstream/src
```

Thanks for all the help btw. :smiley:

**Pull request closed without merging**
