### PR TITLE
jsrocks

### PR DESCRIPTION
**Pull request by robsongajunior**
new jsrocks website

### CODE REVIEW

**Comment by UltCombo** [comment]
Looks like this PR modifies some of the posts' markdown files, as if you were overwriting them with an older version.

**Comment by UltCombo** [comment]
I can help if you describe what exactly needs to be done. As far as I can see, you would just have to delete the templates directory and add the `package.json`, no?

**Comment by jaydson** [comment]
@robsongajunior is trying to push the JSRocks website version (already using the theme feature).
@robsongajunior, the posts are updated, right?

**Comment by UltCombo** [comment]
@jaydson take a look at the diff. Some of the recent posts are deleted, many recent fixes have been reverted as well.
The diff is too dirt, it is easier to open a new PR imo.

**Comment by UltCombo** [comment]
The diff is `+24 −10,313` LoC, at a quick glance ignoring the deleted posts and reverted mistakes, it seems like this should just delete the templates from the repository and add a package.json to pull the theme from https://github.com/es6rocks/harmonic-theme-jsrocks as a dependency.

It would be nice if @robsongajunior can confirm, so we can clean this up.

**Comment by jaydson** [comment]
Things to do before merging:
- [] @robsongajunior must to confirm if the PR is ok, with the latest resources (posts, etc) updated
- [] @jaydson and @UltCombo must test this branch
- [] We need to rename the org to `jsrocks`

Anything else i have missed?

**Comment by UltCombo** [comment]
@jaydson also change the repository name, the readme header and all references to ES6 Rocks in the README and CONTRIBUTING files. And don't forget to change the CNAME to point to the new domain. :stuck_out_tongue_closed_eyes: 
I'm not sure about the Twitter account.

**Comment by jaydson** [comment]
Thanks @UltCombo, i've updated the list.
About the Twitter account, let's just change the label to "JSRocks", but keep @es6rocks.
What do you think?

**Comment by UltCombo** [comment]
@jaydson sounds good to me. :smile:

**Comment by robsongajunior** [comment]
@jaydson @UltCombo  at night i will go verify checklist.
I realy delete old archives and subscribe with new website.

About if the posts are updated, I get of master branch, but will go verify too.

my bad.

**Comment by robsongajunior** [comment]
PR canceled.

About the post...
> Things to do before merging
cc/ @jaydson

What do you think make this list one issue?

**Comment by jaydson** [comment]
Good idea @robsongajunior

**Comment by UltCombo** [comment]
@robsongajunior do you need help with this PR?
@jaydson should this go live asap or we wait until your next conf presentation?

**Pull request closed without merging**
